### ISSUE TITLE
How to Use <Image \> into an existing project?

### ISSUE THREAD

**Issue by thagxt** [RafidMuhymin/astro-image-demo#1]
Can you, please, guide me on how to use this inside my existing project? 
I've already built a site with astro but I'm looking to have all the pros of responsive images etc. 
How can I achieve that? 

Do I've to clone this repo into my existing project  and run the commands described in the readme of this repo. Or I've to move only certain files into my project to make it work? 

Thank you very much.

**Comment by RafidMuhymin** [comment]
The steps described in the `README.md` file are for running the demo project. If you want to use the `<Image />` component in your project, copy the `components`, `utils`, `interfaces`, `styles` folders inside the `src` directory into your project and then import the `<Image />` component from `../path/to/components/Image.astro`.

**Comment by thagxt** [comment]
Thank you. That worked.

Here's what I did. A more detailed way.

1. Copy `dependencies` part from the `package.json` file inside your `package.json`
  ```
    "dependencies": {
      "astro": "^0.21.12",
      "imagetools-core": "^3.0.1",
      "potrace": "^2.1.8",
      "sharp": "^0.29.3",
      "vite-imagetools": "^4.0.1"
    },
  ```

2. Copy these from `astro.config.mjs` into your `astro.config.mjs`
  ```
    vite: {
      plugins: [imagetools()],
    },
    image: {
      formats: ["webp", "png", "jpg", "jpeg", "gif"],
    },
  ``` 

3. Copy the `components`, `utils`, `interfaces`, `styles` directories into your `src` directory.

4. Import `Image` in the files where you need it:
  ```
  ---
  import Image from "../components/Image.astro";
  ---

  <Image
    src="/src/images/elva-800w.jpg"
    alt="A father holiding his beloved daughter in his arms"
    artDirectives={[
      {
        media: "(max-width: 480px)",
        src: "/src/images/elva-480w-close-portrait.jpg",
      },
    ]}
  />
  ```

5. run `npm install` inside your project
6. then `npm start`

**Comment by thagxt** [comment]
I've one more question, is it possible to use this inside `.md` files? Since I've images that I use inside my blog post body...

**Comment by thagxt** [comment]
I'm facing another problem.

If I try to include `Image` inside another component, I get an error:
```
500: Internal Error
Input file is missing
Error: Input file is missing
```

`src/components/BlogPostPreview.astro`
```
---
import Image from "./Image.astro";
export interface Props { post: any; }

const { post } = Astro.props;
---
<!-- this works: <img src={post.heroImage} alt={post.alt} loading="lazy" width="720"> -->

<!-- this gives me the error -->
<Image
    src={post.heroImage}
    alt={post.alt}
    artDirectives={[
    {
        media: "(max-width: 480px)",
        src: `${post.heroImage}`,
    },
    ]}
/>
<h2 class="title">{post.title}</h2>
```

do you have any ideas how I make it work?
Thank you again.

**Comment by RafidMuhymin** [comment]
> I've one more question, is it possible to use this inside `.md` files? Since I've images that I use inside my blog post body...

I haven't tested this but it should work. But you'll have to import the `<Image />` component inside your `.md` files.

**Comment by RafidMuhymin** [comment]
> If I try to include Image inside another component, I get an error:
500: Internal Error
Input file is missing
Error: Input file is missing

What is the value of `post.heroImage`??

**Comment by thagxt** [comment]
`heroImage` is defined in the frontmatter inside the `.md` file, and it's basically the path to the image inside the `src/assets` dir.

```
---
heroImage: /src/assets/home-hero.png
---
```

- If I do `{heroImage}` I get `/src/assets/home-hero.png` 

- This `<img src={heroImage} >` renders the image just fine. 

- This `<Image src={heroImage}` gives me the empty input 500 error.

Also 

This works:
```
<Image
  src="/src/assets/home-hero.png"
  alt="This is a hero image"
/>  
```

This does not:

```
<Image
  src={heroImage}
  alt={alt}
/>

**Comment by thagxt** [comment]
Ok, my bad ... the post I was testing the image path wasn't inside `/src/assets/` but was actually in `public/assets` so you can't have images located in `public/assets/` because you'll get that error (and it seems pretty obvious why).

I've tried to use `<Image` inside `.md` and I'm getting the undefined error here.

**Comment by RafidMuhymin** [comment]
> I've tried to use `<Image />` inside .md and I'm getting the undefined error here.

Isn't the component working inside `.md` files now?? You said previously that it was working if the correct path is provided.

**Comment by niksmac** [comment]
@thagxt any workaround on this yet?

**Comment by RafidMuhymin** [comment]
Closing this issue as it's now unrelated to the repository. If you need more information on how to use the `astro-imagetools` package, check the docs at https://www.npmjs.com/package/astro-imagetools.
