### ISSUE TITLE
Where are images saved?

### ISSUE THREAD

**Issue by bronze** [RafidMuhymin/astro-image-demo#2]
Hi there

Took this for a ride and something is confusing me. When building for prod, the dist folder has only the html (with a couple inlined css images). The sources srcsets point to a `/@imagetools/` folder like:
```
srcset="/@imagetools/78e67e6bf7c1e914075ec1ced702e3b3e9344bf1 320w, /@imagetools/258a21587184c1afbff9f335ac6a4955219fe4c7 480w"
```

Did i screw up something when cloning this project?

cheers

**Comment by RafidMuhymin** [comment]
No, you have screwed up nothing. The demo doesn't build currently as there are some issues with vite plugins like `vite-imagetools`  https://github.com/withastro/astro/issues/1718. The build may work if you run `astro build --experimental-static-build`.

**Comment by bronze** [comment]
ah! yes that does make it difficult. :)

ty!
