### ISSUE TITLE
Vite raising Error [Local Machine]

### ISSUE THREAD

**Issue by lem0n4id** [RafidMuhymin/astro-image-demo#6]
I wanted to try out the demo, so I did the following 👇 
```
npm install
npm start
```

This is raising error on my local machine(i dont know why). However, It **works perfectly fine on gitpod**

Can you help me out?

<details><summary>error log</summary>
```bash
$ npm start

>start
>astro dev

02:49 PM [astro] Server started                               3249ms
02:49 PM [astro] Local: http://127.0.0.1:3000/
2:49:47 pm [vite] Error when evaluating SSR module /node_modules/astro-imagetools/src/component/utils/getImage.js:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (F:\codes\astro-image-demo\node_modules\vite\dist\node\chunks\dep-971d9e33.js:56176:28)
2:49:47 pm [vite] Error when evaluating SSR module /node_modules/astro-imagetools/src/component/utils/renderImage.js:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (F:\codes\astro-image-demo\node_modules\vite\dist\node\chunks\dep-971d9e33.js:56176:28)
2:49:47 pm [vite] Error when evaluating SSR module /node_modules/astro-imagetools/src/component/Image.astro:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (F:\codes\astro-image-demo\node_modules\vite\dist\node\chunks\dep-971d9e33.js:56176:28)
2:49:47 pm [vite] Error when evaluating SSR module F:\codes\astro-image-demo\src\pages\index.astro:
SyntaxError: Unexpected token '||='
    at new AsyncFunction (<anonymous>)
    at instantiateModule (F:\codes\astro-image-demo\node_modules\vite\dist\node\chunks\dep-971d9e33.js:56176:28)
02:49 PM [astro] 500 /
```</details>

**Comment by RafidMuhymin** [comment]
@lem0n4id Maybe you're using an old version of NodeJS as the errors are saying `Unexpected token '||='`. The MDN documentation for the [Logical OR assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment) operator says that since `v15.0.0` it's supported in NodeJS. Can you confirm if upgrading to `v15` or a newer version fixes this problem?

**Comment by tiptopweb** [comment]
I had the same error as above, and some others like

`(node:7192) UnhandledPromiseRejectionWarning: TypeError: process.cwd(...).replaceAll is not a function
    at file:///C:/Users/thier/Desktop/astro-image-demo-main/astro-image-demo-main/node_modules/astro-imagetools/src/plugin/index.js:14:27`
    
I update to node v16.14.2 and it is working
You probably can close that issue

**Comment by RafidMuhymin** [comment]
Closing this issue for now. Feel free to reopen the issue if necessary.

**Comment by lem0n4id** [comment]
Yup you are right @RafidMuhymin ! I had NodeJS `v14.17.4`. It works after I now updated to `v16.14.2`.  Thanks!
